### ISSUE TITLE
Feature request: Shortcut to given query

### ISSUE THREAD

**Issue by maxdd** [mancuniancol/script.module.magnetic#1]
Hello,
what about adding a feature that allow to add in the addon list near TV Shows/Movies/Search a given search term in order to automate the process.
This will allow us to put it in the Kodi favourites as well.
For example, i'm searching MoviesXYZ S03 and after the search you are requested to add it in your list so that next time pressing the item in the list will lead to an automatic search. This way one can add an entire season for example.
It is similar to the history but more useful i think.

**Comment by mancuniancol** [comment]
I am not sure how I can implement that. It seems more a request for Quasar or Torrenter. Because, even if I send the information. At the end, they will ignore the extra information.
