### ISSUE TITLE
Error installing magnetic manager:Address already in use

### ISSUE THREAD

**Issue by MattMuffin** [mancuniancol/script.module.magnetic#2]
Hello,

I get this Python error:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'socket.error'>
Error Contents: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/script.module.magnetic/service.py", line 46, in 
server = ThreadedHTTPServer((PROVIDER_SERVICE_HOST, PROVIDER_SERVICE_PORT), ProvidersHandler)
File "/usr/lib/python2.7/SocketServer.py", line 420, in init
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
-->End of Python script error report<--

I've tested on Ubuntu, I dont have this error; it only appears on the RPi2 / ARMv7 architecture.

Here's what I found:

netstat -tulpn | grep 5005
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:5005          0.0.0.0:*               LISTEN      -   

sudo fuser 5005/tcp
5005/tcp:              371
sudo ls -l /proc/371/exe
lrwxrwxrwx 1 root root 0 Nov 19 22:30 /proc/371/exe -> /usr/lib/kodi/kodi.bin

So I guess Kodi is the culprit? I did not have this issue on Jarvis. Is there a default setting that sets the port to 5005?

Also, changing that port in utils.py will have an impact of quasar or it doesnt matter?

Thanks

**Comment by mancuniancol** [comment]
It is possible that you have another addon that took that port or kodi itself. But, the result is the same. It blocks magnetic. 

About your las question. Short answer: No.  
Long answer: Magnetic is independent of Quasar. I remind you that you use it with Torrenter V2 or other torrent player using magnetic contextual menu.

**Comment by mancuniancol** [comment]
I am going to close this issue.
