### ISSUE TITLE
fix for italian translation

### ISSUE THREAD

**Issue by lollo78** [mancuniancol/script.module.magnetic#5]
Hi mancuniancol, 
in my italian translation there are two errors that require a quick fix.

There are a space after "/" into the COLOR tags ( [/ COLOR] ). 
So the yellow code in not processed.

This is the right ones:

```
#: setting.xml
msgctxt "#32010"
msgid "[COLOR FFffd800]Magnetizer...[/COLOR]"
msgstr "[COLOR FFffd800]Magnetizzatore...[/COLOR]"
```

and 

```
#: settings.xml
msgctxt "#32074"
msgid "[COLOR FFffd800]Magnetizer[/COLOR] Results for %s"
msgstr "[COLOR FFffd800]Magnetizzatore[/COLOR] Risultati per %s"
```

Please, add them in the master code
Thx
Bye!

**Comment by mancuniancol** [comment]
It is done. I've found another problem in other languages.  Thank you for the feedback.
